### ISSUE TITLE
Problem with Solana Trading View

### ISSUE THREAD

**Issue by 486xtm** [486xtm/photon-sol#3]
My project is using Next.
There is a Solana Trading View  Homepage.
I want to add tradingView widget on my project.
If you have experience of that especially for this field, help me.

**Comment by asilenced** [comment]
Hi @486xtm .
follow these steps and you will get success.

import { useEffect, useRef } from 'react';

const SolanaTradingViewWidget = () => {
  const containerRef = useRef();

  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://s3.tradingview.com/tv.js';
    script.async = true;
    script.onload = () => {
      new window.TradingView.widget({
        container_id: containerRef.current.id,
        width: '100%',
        height: 500,
        symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance
        interval: 'D',
        timezone: 'Etc/UTC',
        theme: 'dark',
        style: '1',
        locale: 'en',
        toolbar_bg: '#f1f3f6',
        enable_publishing: false,
        withdateranges: true,
        hide_side_toolbar: false,
        allow_symbol_change: true,
        show_popup_button: true,
        popup_width: '1000',
        popup_height: '650',
      });
    };
    document.body.appendChild(script);
  }, []);

  return <div id="tradingview-widget" ref={containerRef} className="tradingview-widget-container" />;
};

export default SolanaTradingViewWidget;

**Comment by 486xtm** [comment]
> Hi @486xtm . follow these steps and you will get success.
> 
> import { useEffect, useRef } from 'react';
> 
> const SolanaTradingViewWidget = () => { const containerRef = useRef();
> 
> useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> 
> return
> 
> ;
> };
> export default SolanaTradingViewWidget;

Thanks.
But how can I use this componet?

**Comment by asilenced** [comment]
> > Hi @486xtm . follow these steps and you will get success.
> > import { useEffect, useRef } from 'react';
> > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > return
> > ;
> > };
> > export default SolanaTradingViewWidget;
> 
> Thanks. But how can I use this componet?

You can add this component to the landing page and show the process.

**Comment by 486xtm** [comment]
> > > Hi @486xtm . follow these steps and you will get success.
> > > import { useEffect, useRef } from 'react';
> > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > return
> > > ;
> > > };
> > > export default SolanaTradingViewWidget;
> > 
> > 
> > Thanks. But how can I use this componet?
> 
> You can add this component to the landing page and show the process.



> > > Hi @486xtm . follow these steps and you will get success.
> > > import { useEffect, useRef } from 'react';
> > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > return
> > > ;
> > > };
> > > export default SolanaTradingViewWidget;
> > 
> > 
> > Thanks. But how can I use this componet?
> 
> You can add this component to the landing page and show the process.

Thanks @asilenced , your suggestion resolved the issue! I'll go ahead and close this now.

**Comment by 486xtm** [comment]
> > > > Hi @486xtm . follow these steps and you will get success.
> > > > import { useEffect, useRef } from 'react';
> > > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > > return
> > > > ;
> > > > };
> > > > export default SolanaTradingViewWidget;
> > > 
> > > 
> > > Thanks. But how can I use this componet?
> > 
> > 
> > You can add this component to the landing page and show the process.
> 
> > > > Hi @486xtm . follow these steps and you will get success.
> > > > import { useEffect, useRef } from 'react';
> > > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > > return
> > > > ;
> > > > };
> > > > export default SolanaTradingViewWidget;
> > > 
> > > 
> > > Thanks. But how can I use this componet?
> > 
> > 
> > You can add this component to the landing page and show the process.
> 
> Thanks @asilenced , your suggestion resolved the issue! I'll go ahead and close this now.

You can add this component to the landing page and show the process.

**Comment by asilenced** [comment]
> > > > > Hi @486xtm . follow these steps and you will get success.
> > > > > import { useEffect, useRef } from 'react';
> > > > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > > > return
> > > > > ;
> > > > > };
> > > > > export default SolanaTradingViewWidget;
> > > > 
> > > > 
> > > > Thanks. But how can I use this componet?
> > > 
> > > 
> > > You can add this component to the landing page and show the process.
> > 
> > 
> > > > > Hi @486xtm . follow these steps and you will get success.
> > > > > import { useEffect, useRef } from 'react';
> > > > > const SolanaTradingViewWidget = () => { const containerRef = useRef();
> > > > > useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> > > > > return
> > > > > ;
> > > > > };
> > > > > export default SolanaTradingViewWidget;
> > > > 
> > > > 
> > > > Thanks. But how can I use this componet?
> > > 
> > > 
> > > You can add this component to the landing page and show the process.
> > 
> > 
> > Thanks @asilenced , your suggestion resolved the issue! I'll go ahead and close this now.
> 
> You can add this component to the landing page and show the process.

Thanks @486xtm, your suggestion resolved the issue! I'll go ahead and close this now.
